apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: subscribers-app-role
  annotations:
    crossplane.io/external-name: subscribers-app-role
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Federated": "arn:aws:iam::${AWS_ACCOUNT_ID}:oidc-provider/${OIDC_PROVIDER}"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
              "StringEquals": {
                "${OIDC_PROVIDER}:sub": "system:serviceaccount:subscribers-app:subscribers-app",
                "${OIDC_PROVIDER}:aud": "sts.amazonaws.com"
              }
            }
          }
        ]
      }
    description: "Role for subscribers-app to access SQS and SNS"
    tags:
      Name: subscribers-app-role
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicy
metadata:
  name: subscribers-app-policy
  annotations:
    crossplane.io/external-name: subscribers-app-policy
spec:
  forProvider:
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "sqs:SendMessage",
              "sqs:ReceiveMessage",
              "sqs:DeleteMessage",
              "sqs:GetQueueAttributes"
            ],
            "Resource": "*"
          },
          {
            "Effect": "Allow",
            "Action": [
              "sns:Publish",
              "sns:Subscribe",
              "sns:Unsubscribe"
            ],
            "Resource": "*"
          }
        ]
      }
    role: subscribers-app-role 