replicaCount: 1

image:
  repository: ghcr.io/stavocha/no-more-dev-env-headaches/myapp
  tag: latest
  pullPolicy: IfNotPresent

serviceAccount:
  create: true

env:
  AWS_REGION: us-east-1

service:
  type: ClusterIP
  port: 5000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80 