apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ${var.chart_repo_url}
    targetRevision: ${var.chart_revision}
    path: argocd/charts/crossplane
    helm:
      parameters:
        - name: aws.roleArn
          value: ${aws_iam_role.crossplane_aws_role.arn}
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
